language: go

go:
- 1.13.x
- 1.14.x
- 1.15.x
- tip

os:
- linux
- windows
- osx

before_install:
- go get github.com/mattn/goveralls

script:
- $GOPATH/bin/goveralls -service=travis-ci -show -debug -shallow
- go test -v -bench=.

matrix:
    allow_failures:
        - os: osx

